
package restWS.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.2
 * Wed Jan 31 16:33:05 CET 2024
 * Generated source version: 3.6.2
 */

@XmlRootElement(name = "direBonjour", namespace = "http://restWS/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "direBonjour", namespace = "http://restWS/")

public class DireBonjour {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

