package soapWS.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.9
 * Tue Jan 30 09:09:31 GMT+01:00 2024
 * Generated source version: 2.7.9
 */

@XmlRootElement(name = "direBonjour", namespace = "http://soapWS/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "direBonjour", namespace = "http://soapWS/")

public class DireBonjour {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}